Floofbot/Modules/Fun.cs

Added 8-Ball command

---

Floofbot/Modules/Logging.cs
Floofbot/Program.cs

The structure of the module has been updated to work with Entity Framework instead of directly Sqlite. Also, some basic exception handling has been added.

Updated Event Logging to Work With Entity Framework

---

.gitignore
Floofbot/Program.cs
Floofbot/app.config.sample

- Add app.config to gitignore and delete it from the repository
- Create a sample app.config file so users know what fields are needed
- The program now doesn't take in a parameter for the token

Add Token field to app.config

---

Floofbot/Modules/Administration.cs

- Give the usage in the case the user
forgets to give one
- Add [Remainder]

Adjust the warn method

---

Discord.Addons.Interactive/Callbacks/IReactionCallback.cs
Discord.Addons.Interactive/Criteria/Criteria.cs
Discord.Addons.Interactive/Criteria/EmptyCriterion.cs
Discord.Addons.Interactive/Criteria/EnsureFromUserCriterion.cs
Discord.Addons.Interactive/Criteria/EnsureSourceChannelCriterion.cs
Discord.Addons.Interactive/Criteria/EnsureSourceUserCriterion.cs
Discord.Addons.Interactive/Criteria/ICriteria.cs
Discord.Addons.Interactive/Discord.Addons.Interactive.csproj
Discord.Addons.Interactive/InlineReaction/InlineReactionCallback.cs
Discord.Addons.Interactive/InlineReaction/ReactionCallbackData.cs
Discord.Addons.Interactive/InlineReaction/ReactionCallbackItem.cs
Discord.Addons.Interactive/InteractiveBase.cs
Discord.Addons.Interactive/InteractiveService.cs
Discord.Addons.Interactive/Paginator/EnsureIsIntegerCriterion.cs
Discord.Addons.Interactive/Paginator/EnsureReactionFromSourceUserCriterion.cs
Discord.Addons.Interactive/Paginator/PaginatedAppearanceOptions.cs
Discord.Addons.Interactive/Paginator/PaginatedMessage.cs
Discord.Addons.Interactive/Paginator/PaginatedMessageCallback.cs
Discord.Addons.Interactive/Paginator/ReactionList.cs
Discord.Addons.Interactive/Results/OkResult.cs
Floofbot.sln
Floofbot/Floofbot.csproj
Floofbot/Modules/Help.cs
Floofbot/Modules/Utilities.cs

The current available pagination modules are outdated, so a local copy of the project has been imported and updated to work with discord.net v2.2.0. A basic help command has been implemented that will be refactored and improved in future PRs.

Implemented Help Command and Pagination

---

Floofbot/Modules/NicknameAlert.cs
Floofbot/Services/NicknameAlertService.cs

The NicknameAlertService was completed and will be integrated with the filter and event logger in a future PR. Some mild bugs have also been fixed in related commands.

Completed The NicknameAlertService

---

Floofbot/Services/EventLoggerService.cs

The event logger service is updated to not post bot messages

Added A Check To Not Post Bot Messages In The Event Logger

---

Floofbot/Modules/Help.cs

A command has been added that returns module-specific help, detailing parameters
Summaries have also been added

Added Command For Specific Module Help

---

Floofbot/Modules/Fun.cs
Floofbot/Modules/Helpers/GameBoard.cs

added minesweeper command

---

Floofbot/Handlers/CommandHandler.cs

Thanks to @iShauny for the code pointer

Make commands case-insensitive

---

Floofbot/Handlers/CommandHandler.cs
Floofbot/Modules/Fun.cs
Floofbot/Modules/Helpers/EightBall.cs

This how the change looks in action:

Add 8ball responses to bot highlights that end with "?"

---

Floofbot/Modules/Utilities.cs
Floofbot/Services/EventLoggerService.cs

Few of the timestamps in the code were in US format. This PR changes those that I could find to RF1123 "short" format.
This is how this change set looks in action

RFC1123 timestamps

---

Floofbot/Handlers/CommandHandler.cs
Floofbot/Services/EventLoggerService.cs

The behavior is now moved to `EventLoggerService.OnMessage` so it will be run in an `async` context

Move EightBall question

---

Floofbot/Modules/Administration.cs

Warning: if we're logging deletes for the purge command, then the delete messages will be rate-limited because the deletions are occurring too quickly.

Create purge command

---

Floofbot/Migrations/20200707143357_Usernotes.Designer.cs
Floofbot/Migrations/20200707143357_Usernotes.cs
Floofbot/Modules/Administration.cs
Floofbot/Services/Repository/FloofDataContext.cs
Floofbot/Services/Repository/Models/UserNote.cs

User notes have been added alongside the framework for forgiving users (removing warnings)

Added user notes

---

Floofbot/Modules/Administration.cs

The prune command now uses the build in discord bulk delete function and takes the number of days to prune as a parameter

Change prune command

---

Floofbot/Modules/TagCommands.cs

Updated tag admin check to use ban members instead of administrator permissions

Updated tag admin check

---

Floofbot/Floofbot.csproj
Floofbot/Modules/Administration.cs

+ Commands have been added that allow moderators to forgive and unforgive warnings/usernotes
+ Warnlog has been updated to show this

Added commands to forgive/unforgive warnings

---

Floofbot/Modules/Administration.cs

Users can now view their own warn logs which are DMd to them, moderators can view their own warn logs or other user's.

Added the ability for users to view their own warnlog + minor refactoring

---

Floofbot/Modules/Administration.cs

This allows moderators to add a warning/usernote to the database for a specific user via their user id if they are not in the server

Add the ability for moderators to warn/add usernotes to people not in the server

---

Floofbot/Modules/Administration.cs

This allows admins to purge the messages of users who have left or been banned

Added option to purge via User ID

---

Floofbot/Configs/BotConfig.cs
Floofbot/Program.cs
Floofbot/Services/Repository/FloofDataContext.cs
Floofbot/app.config.sample

Also added the database file path to the config file

Added Support To Specify App Config in Command Line Argument

---

Floofbot/Handlers/CommandHandler.cs
Floofbot/Program.cs

The reporting of errors has been improved in readability and the message cache size has been increased to 1000.

Improved Error Logging Readability and Increase Cache Size

---

Floofbot/Handlers/CommandHandler.cs

Users can now edit their messages to use the bot command handler

Implement Edited Message Command Handler

---

.github/workflows/main.yml

This builds binaries for 3 targets (all x86-64):
* Windows
* Linux
* Linux (musl libc)

Add basic build action

---

Floofbot/Configs/BotConfig.cs
Floofbot/Program.cs
Floofbot/Scripts/LinuxDBBackup.sh
Floofbot/Scripts/WindowsDBBackup.ps1
Floofbot/Services/BackupService.cs
Floofbot/app.config.sample
Floofbot/scripts/testing.ps1

A c# backup routine has been provided
Two basic SQLite backup scripts have also been provided
Config file has been updated to reflect these changes

Created Basic Backup Routine

---

Floofbot/Handlers/CommandHandler.cs

Fixes bot responding to a message starting with multiple prefixes in a row

---

Floofbot/Configs/BotConfig.cs
Floofbot/Modules/TagCommands.cs
Floofbot/Services/RaidProtectionService.cs
Floofbot/app.config.sample

Various hotfixes for different modules have been grouped together in this PR

Implemented Various Hotfixes

---

Discord.Addons.Interactive/Discord.Addons.Interactive.csproj
Floofbot/Floofbot.csproj
Floofbot/Modules/Utilities.cs

Userinfo:
- Nickname and Username+discriminant have been put on the same line
- Date and times have been set to UTC, and full letters months have been added for clarity
Serverinfo:
- Date and times have been set to UTC, and full letters months have been added for clarity

Userinfo and Serverinfo: Add some clarity to Username and date/time

---

Floofbot/Services/BackupService.cs
Floofbot/Services/EventLoggerService.cs
Floofbot/Services/RaidProtectionService.cs

* Fixes some (but not all) exceptions when a user messages the bot in a DM
* Fixes backups running multiple times per day

Minor fixes

---

Floofbot/Handlers/CommandHandler.cs
Floofbot/Services/EventLoggerService.cs

This prevents bugs where the 8ball question will be detected as a potential command

Moved 8ball and random response to command handler

---

Floofbot/Modules/Utilities.cs

Say command now automatically deletes origin message.
Also yes, I messed up my commits on the branch.

Update on Say command

---

Floofbot/Services/EventLoggerService.cs

This allows for filtered phrases rather than just words

Added regex into a group to allow phrases with spaces

---

Floofbot/Handlers/CommandHandler.cs
Floofbot/Modules/Administration.cs
Floofbot/Services/EventLoggerService.cs

- String content has been changed to be less confrontational to users
- A bug has been fixed where warnlog would error if resolve user returned null

String QoL Changes and Minor Warnlog Bug Fix

---

Floofbot/Modules/Fun.cs
Floofbot/Modules/Utilities.cs

- URI checks have been added to the image fetchers to handle fatal errors
- Preconditions have been added to the avatar command

Various bugfixes

---

Floofbot/Modules/TagCommands.cs

Tags can only now be used in the server they were created in

Restricted Tag Usage to Server Only Tags

---

Floofbot/Modules/Administration.cs

This will allow the ban to be processed even if the bot cannot send messages to the user or channel

Moved message sending to end of command

---

Floofbot/Configs/BotConfig.cs
Floofbot/Modules/Administration.cs
Floofbot/Services/EventHandlerService.cs
Floofbot/config.yaml.sample

Rules gate is no longer a command and now only requires a user to respond with "yes" in there message to accept the rules

Moved rules gate to an event handler

---

Floofbot/Services/RaidProtectionService.cs
Floofbot/config.yaml.sample

Raid protection will now filter out repeated phrases alongside characters

Added phrase detection

---

Floofbot/Floofbot.csproj
Floofbot/Migrations/20210112225014_WelcomeGate.Designer.cs
Floofbot/Migrations/20210112225014_WelcomeGate.cs
Floofbot/Modules/WelcomeGateConfig.cs
Floofbot/Services/EventHandlerService.cs
Floofbot/Services/Repository/FloofDataContext.cs
Floofbot/Services/Repository/Models/WelcomeGate.cs
Floofbot/Services/WelcomeGateService.cs

This auto adds a predefined role to a user when they pass the welcome gate

Created Welcome Gate Service

---

Floofbot/Services/RaidProtectionService.cs

Raid protection will now detect animated emojis

Added raid service animated emoji support

---

Floofbot/Services/RaidProtectionService.cs

Raid detection correctly detects unicode emojis

Fixed unicode emoji detection

---

Floofbot/Services/RaidProtectionService.cs

Phase detection no longer detected spaces in repeated phrases eg "e " vs "e".

Removed spaces in phrase detection

---

Floofbot/Services/EventHandlerService.cs
Floofbot/Services/NicknameAlertService.cs
Floofbot/Services/WordFilterService.cs

- Nickname alert now shows the filtered words it detected in a users name/nickname
- Made nickname alert service independent from the event handler toggling and logging

Nickname alert now shows detected filtered words

---

Floofbot/Services/EventHandlerService.cs

- Null check added for the GetChannel function
- Toggle check moved along with filter check above the GetChannel call

Fixed bugs in event logging

---

Floofbot/Services/EventHandlerService.cs

Nckname alerts only trigger when nicknames are different, not on all user changes

Added nickname check on nickname alert

---

Floofbot/Modules/Administration.cs

This command will kick a user from the server without notifying them

Added silent kick command

---

Floofbot/Modules/Fun.cs

Added pre-text and enclosed in embed. Also prevents using the command with only one choice

Updated choice command

---

ansible/basic_inventory.yaml
ansible/files/cloud_backup.sh.j2
ansible/files/manage_floofbot.sh.j2
ansible/prep_ansible_playbook.yaml
ansible/prep_floofbot_playbook.yaml
ansible/vars/default.yaml

Add bot container management script
Add Dropbox backup script
No real documentation yet, but that'll be coming soon on the ops documentation site.

Add playbook for setting up a machine for Floofbot

---

Floofbot/Floofbot.csproj
Floofbot/Modules/ModMail.cs
Floofbot/Modules/Utilities.cs
Floofbot/Modules/WelcomeGateConfig.cs

I noticed some of the help pages were not having correct naming and instead only had the group module name. I added the Name Tag for the ones that did not have one!

Fixed some titles on the help page + added about command with github link!

---

Dockerfile
Floofbot/Floofbot.csproj

This fixes running the bot in an Alpine container. See this for details: https://github.com/discord-net/Discord.Net/issues/2704

Fix running in Alpine
