Floofbot/Floofbot.csproj, Floofbot/Handlers/CommandHandler.cs
Paged responses are now available using `PagedReplyAsync`.
Any module that is using this library must now extend `InteractiveBase` rather than `ModuleBase<SocketCommandContext>`. The former extends the latter anyway.
=> Add Interactive library

Floofbot/Handlers/CommandHandler.cs
This will allow users to mention the bot to use command eg "@FloofBot ping"
Useful if two bots have the same prefix or users are unsure what the prefix is/dont want to use it
=> Added Bot Prefix Command Call

Floofbot/Modules/Administration.cs
Mods can now search the warning history of users not in the server by supplying their user ID. The system will check the database for that user ID
=> Added being able to search warnlogs of users not in server

Floofbot/Migrations/20200707170117_BanOnJoin.Designer.cs, Floofbot/Migrations/20200707170117_BanOnJoin.cs, Floofbot/Modules/Administration.cs, Floofbot/Services/EventLoggerService.cs, Floofbot/Services/Repository/FloofDataContext.cs, Floofbot/Services/Repository/Models/BanOnJoin.cs
Sometimes when a user leaves before the mods can ban them, the api is unable to find the user. This feature allows the mods to provide a user ID that will be added to the database and banned whenever they rejoin the server
=> Added an Auto Ban On User Join

Floofbot/Floofbot.csproj, Floofbot/Migrations/20200708223402_WarnLogUpdate.Designer.cs, Floofbot/Migrations/20200708223402_WarnLogUpdate.cs, Floofbot/Modules/Administration.cs, Floofbot/Services/Repository/Models/Warning.cs
A clickable hyperlink has been added which links to the original warning message. This allows moderators to jump to when the user was warned to get context about the warning
=> Updated warnlog to have clickable hyperlink to warning

Floofbot/Migrations/20200822094523_RaidProtection.Designer.cs, Floofbot/Migrations/20200822094523_RaidProtection.cs, Floofbot/Modules/RaidProtectionCommands.cs, Floofbot/Services/EventLoggerService.cs, Floofbot/Services/RaidProtectionService.cs, Floofbot/Services/Repository/FloofDataContext.cs, Floofbot/Services/Repository/Models/RaidProtectionConfig.cs
The rules for triggering the raid protection are:
- Over 10 Mass mention spams (instant ban)
- Over 3 user strikes within 5 mins
- - Can gain from spamming 5 messages in 5 seconds
- - Can gain from posting invite links
- - Can gain from spamming the same letter over 5 times in a row
- - Can gain from spamming 5 emojis both custom and normal
- After 5 minutes, the user is forgiven
Mod alerts when
- Over 3 users have been punished within 30 mins
- Over 5 users joined in 2 mins
- A user has been autobanned for mention spam
Options:
- Toggle on/off the raid protection
- Set a muted role
- Set a mod role to ping for alerts
- Set a mod channel to send mod alerts to
- Toggle on/off banning instead of muting (mute role must be set to disable this)
- Add an exceptions role which is not affected by …
=> Added Basic Raid Protection Service and Commands

Floofbot/Handlers/CommandHandler.cs, Floofbot/Modules/Filter.cs, Floofbot/Modules/UserAssignableRoleCommands.cs
* Prevents errors from getting eaten when they are raised from a command issued in a DM.
* Change the word filter add/remove commands to not require the use of quotes
* Enforced guild context requirement for iam/iamnot commands
=> Various minor fixes

Floofbot/Handlers/CommandHandler.cs
This prevents commands from being fired twice when a large embed image preview is posted, which triggers the edited message handler
=> Ignore edited messages if content is same

Floofbot/Modules/Fun.cs
Previously, the XKCD command would just spit out an error message with a
possibly unknown value to some. I changed this around so that it now
gets the latest XKCD comic with no argument given (as it says in the
help command and module summary), as well as gives the actual integer
value for the maximum comic ID.
=> XKCD now gets latest on no argument

Floofbot/Services/EventLoggerService.cs, Floofbot/Services/RaidProtectionService.cs, Floofbot/Services/WordFilterService.cs, Floofbot/config.yaml.sample
- Several parameters have been set to configurable variables
- Users last sent message in a server is now recorded to compare timestamps
- This means that if there is API lag or the discord bot lags, it will not trigger false positives in raid protection
- Word filter service is implemented into raid protection
=> Updated Raid Protection To Include Timestamps

Floofbot/Handlers/RandomResponseGenerator.cs, Floofbot/Services/EventLoggerService.cs
Fixes the message log erroring out when a message with just an attachment gets deleted. Now it logs attachment URLs (which likely can't resolve to an actual file as the message has been deleted)
Also fixes the random response handler erroring out when a system message (i.e. a user joined message or a message has been pinned notification) is received.
=> Miscellaneous fixes

Floofbot/Modules/Administration.cs, Floofbot/Modules/ErrorLoggingCommands.cs, Floofbot/Modules/Filter.cs, Floofbot/Modules/Fun.cs, Floofbot/Modules/Help.cs, Floofbot/Modules/Logging.cs, Floofbot/Modules/ModMail.cs, Floofbot/Modules/NicknameAlert.cs, Floofbot/Modules/RaidProtectionCommands.cs, Floofbot/Modules/TagCommands.cs, Floofbot/Modules/UserAssignableRoleCommands.cs, Floofbot/Modules/Utilities.cs
- Users can only see commands that they have met the preconditions to use (eg guild only, administrator)
- Aliases are only shown if they are alternate aliases. Before the command would show eg "help (aliases: help)" as cmd name counts as an alias. Now only alternate aliases are shown
=> Improved Help Command

Floofbot/Modules/ModMail.cs
This is to prevent users banned from the modmail server from being able to use the command
=> Updated ModMail to check for mutual guilds

.github/workflows/main.yml, Dockerfile
This adds support for basic container building and pushing. The GitHub Actions job will not run unless a `CR_PAT` secret variable is added, but this has been tested on my fork.
To pull the test image from that fork, run `docker pull ghcr.io/jkchen2/floofbot:latest`
EDIT: I should note that when the secret token has been added, built images will be pushed to Beals' repository at `ghcr.io/bealsbe/floofbot`
EDIT 2: Should also mention that `CR_PAT` is a [personal access token with scoped read/write permissions for GitHub Packages](https://docs.github.com/en/free-pro-team@latest/packages/getting-started-with-github-container-registry/migrating-to-github-container-registry-for-docker-images#authenticating-with-the-container-registry). This will allow the CI build to push built images to the …
=> Add basic container building

Floofbot/Services/WordFilterService.cs
Replaced the nickname alert detection to String.Contains() to prevent filtered words containing regex from being parsed
=> Fixed nickname alert regex parsing

.github/workflows/main.yml, Dockerfile
This enables us to access version information from inside the container. Also the curl dependency is for a Dropbox backup script that we'll see in an upcoming PR.
=> Add curl dependency and version environment variable to image

.github/workflows/main.yml, .gitignore, Discord.Addons.Interactive/Discord.Addons.Interactive.csproj, Discord.Addons.Interactive/InteractiveService.cs, Floofbot/Floofbot.csproj, Floofbot/Handlers/CommandHandler.cs, Floofbot/Migrations/20200512215812_modmail.Designer.cs, Floofbot/Migrations/20200512215812_modmail.cs, Floofbot/Program.cs, Floofbot/Services/EventHandlerService.cs, Floofbot/Services/NicknameAlertService.cs, Floofbot/Services/UserRoleRetentionService.cs, Floofbot/Services/WelcomeGateService.cs, Floofbot/Services/WordFilterService.cs
Update to use updated dependencies and code refactor to allow modules to log events. User time in server removed from leaving event to accommodate discord API changes with caching. Future feature will add a user cache service that runs regularly to cache user data.
=> Update dependencies and modules

.gitignore, Floofbot/Modules/Administration.cs, Floofbot/Modules/Fun.cs, Floofbot/Modules/Help.cs, Floofbot/Services/EventHandlerService.cs, Floofbot/Services/RaidProtectionService.cs
Addresses various bug fixes noted by users and moderators:
CHANGES:
- Ensure a username/id is always resolved for all admin commands
- Add protection against a moderator performing actions on themselves or the bot
- Added a check for pruning messages that the message is not a null object (incase this message is deleted whilst the bot is purging or exists in cache but not in discord)
- Updated filter message warn to be less aggressive
- Added try/catch to catch errors where response is not as expected for parsing or permissions are missing
- Added unban command
- Add command aliases to the help page
- Added a moderation command to fetch a user id
- Added event handlers to make the bot join all threads that are updated or created (avoided running a service to check the bot is in all threads …
=> Various bug fixes and feature requests over the last couple years

Floofbot/Floofbot.csproj
Due to an up-date incompatibility between windows and linux, this PR rolls-back the version of SQLite used
=> Roll-back SQLite version

.github/workflows/main.yml
This should fix the deprecated actions problems. Tested on my fork: https://github.com/jkchen2/Floofbot/actions/runs/16018459668
Also, there's a small chance this will result in a permissions error on pushing the Docker image. GitHub may have added permissions requirements for Actions to write to the container registry. Somebody with permissions would need to go in and configure the settings on the package: https://github.com/bealsbe/Floofbot/pkgs/container/floofbot
Then, add this repo and grant it write permissions
=> Update GH Actions for 2025

Floofbot/Modules/Administration.cs, Floofbot/Services/EventHandlerService.cs
This change removes discriminators from the event logger and admin commands as they are no longer used. Also, minor change to the unban command to handle an unknown user exception
=> Remove Discriminators
